static_variables:
  grid:
    dimensions: [21, 21, 5]  # nx, ny, nz
    spacing_x: 5.0  # dx
    spacing_y: 5.0  # dy
    spacing_z: 10.0  # dz
    depth_top: 2000.0  # Depth of the top layer in m
    
    # If using non-uniform grid, specify the size of each grid block individually
    # spacing_x: [10.0, 12.0, 8.0, ...]  # List of dx for each grid block in x-direction
    # spacing_y: [10.0, 9.0, 11.0, ...]  # List of dy for each grid block in y-direction
    # spacing_z: [2.0, 3.0, 1.5, ...]   # List of dz for each grid block in z-direction

    # If the list of non uniform grid spacing is too long, you can also specify a file to read from
    # spacing_x_file: "spacing_x.npy"    # Numpy file containing an array of size (nx,)
    # spacing_y_file: "spacing_y.npy"    # Numpy file containing an array of size (ny,)
    # spacing_z_file: "spacing_z.npy"    # Numpy file containing an array of size (nz,)

    # null_blocks: "null_blocks.npy"  # array of shape (n_null, 3), [[x_i, y_i, z_i], ...] are null blocks

  
  physical_properties:
    permeability:
      # The unit of permeability is Darcy

      # Specify permeability from files
      # k_i: "permeability_i.npy"  # Numpy file containing an array of size (nx, ny, nz) for permeability in x-direction
      # k_j: "permeability_j.npy"  # Numpy file containing an array of size (nx, ny, nz) for permeability in y-direction
      # k_k: "permeability_k.npy"  # Numpy file containing an array of size (nx, ny, nz) for permeability in z-direction

      # Or specify uniform permeability values
      k_x: 1e-13  # Permeability in x-direction in Darcy
      k_y: 1e-13  # Permeability in y-direction in Darcy
      k_z: 1e-13  # Permeability in z-direction in Darcy
    
    porosity:
      # Porosity is unitless, [0, 1]

      # Specify porosity from file
      # phi: "porosity.npy"  # Numpy file containing an array of size (nx, ny, nz) of porosity values

      # Or specify uniform porosity value
      phi: 0.15
    
    pvt_table:
      file: "input_config/pvt_table.csv"  # CSV file containing PVT data
    
    rock_fluid_model:
      file: "input_config/rock_fluid.csv"
  
initial_conditions:
  pressure: 1.2e7
  S_w: 0.25

well_controls:
  injectors:
    rate_grid: "input_config/rate_grid.npy"
  producers:
    bhp_grid: "input_config/bhp_grid.npy"